coursetracker/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('courses/', views.courses_index, name='index'),
    path('courses/<int:course_id>/', views.courses_detail, name='detail'),
    path('courses/create/', views.CourseCreate.as_view(), name='courses_create'),
    path('courses/<int:pk>/update/', views.CourseUpdate.as_view(), name='courses_update'),
    path('courses/<int:pk>/delete/', views.CourseDelete.as_view(), name='courses_delete'),
    path('courses/<int:course_id>/add_lesson/', views.add_lesson, name='add_lesson'),
    path('courses/<int:course_id>/assoc_student/<int:student_id>/', views.assoc_student, name='assoc_student'),
    path('courses/<int:course_id>/unassoc_student/<int:student_id>/', views.unassoc_student, name='unassoc_student'),
    path('students/', views.StudentList.as_view(), name='students_index'),
    path('students/<int:pk>/', views.StudentDetail.as_view(), name='students_detail'),
    path('students/create/', views.StudentCreate.as_view(), name='students_create'),
    path('students/<int:pk>/update/', views.StudentUpdate.as_view(), name='students_update'),
    path('students/<int:pk>/delete/', views.StudentDelete.as_view(), name='students_delete'),
    path('lessons/<int:pk>/', views.lessons_detail, name='lessons_detail'),
    path('lessons/<int:pk>/update/', views.LessonUpdate.as_view(), name='lessons_update'),
    path('lessons/<int:pk>/delete/', views.LessonDelete.as_view(), name='lessons_delete'),
    path('lesson/<int:pk>/add_homework/', views.add_homework, name='add_homework'),
    path('lessons/<int:pk>/HomeWorkDelete/', views.HomeworkDelete.as_view(), name='homework_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('students/<student_id>/add_photo/', views.add_photo, name='add_photo'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date

# Create your models here.

DAYS = (
    ("M", "M-W-F"),
    ("T", "T-TH"),
)
TIMES = (
    ("1", "8:00-9:30 am"),
    ("2", "9:30-11:00 am"),
    ("3", "12:00-1:30 pm"),
    ("4", "1:30-3:00 pm")
)
YEARS = (
    ("0", "Kindergarten"),
    ("1", "1st Grade"),
    ("2", "2nd Grade"),
    ("3", "3rd Grade"),
    ("4", "4th Grade"),
    ("5", "5th Grade"),
    ("6", "6th Grade"),
    ("7", "7th Grade"),
    ("8", "8th Grade"),
    ("9", "Freshman"),
    ("10", "Sophomore"),
    ("11", "Junior"),
    ("12", "Senior"),
)

LD = (
    ("n", "No"),
    ("y", "Yes"),
)

class Student(models.Model):
  name = models.CharField(max_length=50)
  year = models.CharField(max_length=2, choices=YEARS, default=YEARS[0][0])
  learning_difference = models.CharField(max_length=2, choices=LD, default=LD[0][0])

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('students_detail', kwargs={'pk': self.id})

class Course(models.Model):
    title = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)
    day = models.CharField(max_length=1, choices=DAYS, default=DAYS[0][0])
    time = models.CharField(max_length=1, choices=TIMES, default=TIMES[0][0])
    description = models.TextField(max_length=250)
    teacher = models.CharField(max_length=100)
    prereq = models.CharField(max_length=100)
    students = models.ManyToManyField(Student)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse('detail', kwargs={'course_id': self.id})

class Lesson(models.Model):
    title = models.CharField(max_length=100)
    unit = models.PositiveIntegerField(default=1)
    description = models.TextField(max_length=250)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    class Meta:
        ordering = ['unit']

    def __str__(self):
        return f"Unit {self.unit}: {self.title}"

    def get_absolute_url(self):
        return reverse('lessons_detail', kwargs={'pk': self.id})   

class Homework(models.Model):
    task = models.TextField(max_length = 250)
    assign_date = models.DateField('Assign Date')
    due_date = models.DateField("Due Date") 
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)   

    class Meta:
        ordering = ['due_date']

    def __str__(self):
        return f"{self.task}"     
    
class Photo(models.Model):
    url = models.CharField(max_length=200)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for student_id: {self.student_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Lesson, Homework

class LessonForm(ModelForm):
  class Meta:
    model = Lesson
    fields = ['unit', 'title', 'description']

class HomeworkForm(ModelForm):
  class Meta:
    model = Homework
    fields = ['task', 'due_date']    

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Course, Student, Lesson, Homework, Photo
from .forms import LessonForm, HomeworkForm
from datetime import date
import uuid
import boto3
import os


# Create your views here.


def home(request):
    return render(request, "home.html")


def about(request):
    return render(request, "about.html")


@login_required
def courses_index(request):
    courses = Course.objects.filter(user=request.user)
    return render(request, "courses/index.html", {"courses": courses})


@login_required
def courses_detail(request, course_id):
    course = Course.objects.get(id=course_id)
    id_list = course.students.all().values_list("id")
    students_not_in_course = Student.objects.exclude(id__in=id_list)
    lesson_form = LessonForm()
    return render(
        request,
        "courses/detail.html",
        {
            "course": course,
            "lesson_form": lesson_form,
            "students": students_not_in_course,
        },
    )


@login_required
def add_lesson(request, course_id):
    form = LessonForm(request.POST)
    if form.is_valid():
        new_lesson = form.save(commit=False)
        new_lesson.course_id = course_id
        new_lesson.save()
    return redirect("detail", course_id=course_id)


class CourseCreate(LoginRequiredMixin, CreateView):
    model = Course
    fields = ["title", "subject", "teacher", "day", "time", "description", "prereq"]

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class CourseUpdate(LoginRequiredMixin, UpdateView):
    model = Course
    fields = ["subject", "teacher", "day", "time", "description", "prereq"]


class CourseDelete(LoginRequiredMixin, DeleteView):
    model = Course
    success_url = "/courses/"


class StudentList(LoginRequiredMixin, ListView):
    model = Student


class StudentDetail(LoginRequiredMixin, DetailView):
    model = Student

class StudentCreate(LoginRequiredMixin, CreateView):
    model = Student
    fields = "__all__"


class StudentUpdate(LoginRequiredMixin, UpdateView):
    model = Student
    fields = ["name", "year", "learning_difference"]


class StudentDelete(LoginRequiredMixin, DeleteView):
    model = Student
    success_url = "/students/"


@login_required
def lessons_detail(request, pk):
  lesson = Lesson.objects.get(id=pk)
  homework_form = HomeworkForm()
  return render(request, 'main_app/lesson_detail.html', {'lesson': lesson, 'homework_form': homework_form})
  
@login_required
def add_homework(request, pk):
  form = HomeworkForm(request.POST)
  if form.is_valid():
    new_homework = form.save(commit=False)
    new_homework.lesson_id = pk
    new_homework.assign_date = date.today()
    new_homework.save()
  return redirect('lessons_detail', pk=pk) 

class LessonUpdate(LoginRequiredMixin, UpdateView):
  model = Lesson
  fields = ['title', 'unit', 'description']

class LessonDelete(LoginRequiredMixin, DeleteView):
  model = Lesson
  success_url = '/courses/' 

class HomeworkDelete(LoginRequiredMixin, DeleteView):
  model = Homework
  success_url = '/courses/' 



@login_required
def assoc_student(request, course_id, student_id):
    Course.objects.get(id=course_id).students.add(student_id)
    return redirect("detail", course_id=course_id)


@login_required
def unassoc_student(request, course_id, student_id):
    course = Course.objects.get(id=course_id)
    course.students.remove(student_id)
    return redirect("detail", course_id=course_id)

def signup(request):
    error_message = ""
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("index")
        else:
            error_message = "Invalid sign up - try again"
    form = UserCreationForm()
    context = {"form": form, "error_message": error_message}
    return render(request, "registration/signup.html", context)


def add_photo(request, student_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Photo.objects.create(url=url, student_id=student_id)
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('students_detail', pk=student_id)

main_app/templates/courses/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Course Details</h1>
<div class="row">
  <div class="col s12">
    <div class="card teal lighten-5" id="coursedetail">
      <div class="card-content">
        <span class="card-title">{{ course.title }}</span>
        <p>Subject: {{ course.subject }}</p>
        <p>Teacher: {{ course.teacher }}</p>
        <p>Day: {{ course.get_day_display }}</p>
        <p>Time: {{ course.get_time_display }}</p>
        <p>Description: {{ course.description }}</p>
        <p>Prereqs: {{ course.prereq }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'courses_update' course.id %}">Edit</a>
        <a href="{% url 'courses_delete' course.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col s6">
    <h4>Add Lessons:</h4>
    <form action="{% url 'add_lesson' course.id %}" method="POST">
      {% csrf_token %}
      {{ lesson_form.as_p }}
      <input type="submit" class="btn" value="Add Lesson">
    </form>
    <br>
  </div>
  <div class="col s6">
    <h4>{{ course.title }}'s Lessons:</h4>
    <table class="striped">
      <thead>
        <tr><th>Unit</th><th>Title</th><th>Description</th></tr>
      </thead>
      <tbody>
        {% for lesson in course.lesson_set.all %}
          <tr>
            <td>{{lesson.unit}}</td>
            <td>{{lesson.title}}</td>
            <td>{{lesson.description}}</td>
            <td><a href="{% url 'lessons_detail' lesson.id %}">View Lesson</a></td>
          </tr>     
        {% endfor %}
      </tbody>
    </table>
  </div>

</div>
 
<div class="row">
  <div class="col s6">
    <h4>{{ course.title }}'s Students: </h4>
    {% if course.students.count %}
      {% for student in course.students.all %}
        <div class="card teal lighten-5">
          <div class="card-content">
            <span class="card-title">
              {{ student.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'unassoc_student' course.id student.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Students</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h4>Available Students: </h4>
    {% if students.count %}
      {% for student in students.all %}
        <div class="card teal lighten-5">
          <div class="card-content">
            <span class="card-title">
              {{ student.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_student' course.id student.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h4>{{course.name}} Already Has All Students</h4>
    {% endif %}
  </div>
</div>


{% endblock %}

main_app/templates/courses/index.html
{% extends 'base.html' %} {% block content %}

<h1>Course List</h1>

<div class="row">
{% for course in courses %}
<div class="col s4">
<div class="card teal lighten-5">
  <a href="{% url 'detail' course.id %}">
    <div class="card-content">
      <span class="card-title">{{ course.title }}</span>
      <!-- <p>Subject: {{ course.subject }}</p>
      <p>Teacher: {{ course.teacher }}</p>
      <p>Day: {{ course.get_day_display }}</p>
      <p>Time: {{ course.get_time_display }}</p>
      <p>Description: {{ course.description }}</p>
      <p>Prereqs: {{ course.prereq }}</p> -->
    </div>
  </a>
</div>
</div>
{% endfor %}
</div>

{% endblock %}